config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  resources :users
  resources :sessions, only: [:new, :create, :destroy]

  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/document.rb
class Document < ApplicationRecord
  has_rich_text :content
  serialize :value, JSON
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user

  def current_user
    if session[:user_id]
      @current_user ||= User.find(session[:user_id])
    else
      @current_user = nil
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_email(params[:email])

    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_url, notice: "You've logged in!"
    else
      # Use now for this flash to only last for this action
      flash.now.alert = "Failed to log in"
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: "You've logged out!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/home/index.html.erb
<% if current_user %>
  Logged in as <%= current_user.email %>.
  <%= link_to "Sign Up", signup_path %> or <%= link_to "Log In", login_path %>
<% end %>

<p id="notice"><%= notice %></p>

<section class="hero is-fullheight is-dark is-bold">
  <div class="hero-body">
    <div class="container">
      <h1 class="title is-family-monospace">
        ED
      </h1>
      <h2 class="subtitle">
        for all your education needs
      </h2>
    </div>
  </div>
</section>

app/views/layouts/_navbar.html.erb
<nav class="navbar is-light" role="navigation" aria-label="main navigation">
  <div class="navbar-brand">
    <a class="navbar-item" href="/">
      <h1 class="is-family-monospace is-size-4">ED</h1>
    </a>

    <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
    </a>
  </div>

  <div id="navbarBasicExample" class="navbar-menu">
    <div class="navbar-start">
      <%= link_to 'Home', '/', class: 'navbar-item' %>
      <%= link_to 'Users', '/users', class: 'navbar-item' %>
      <%= link_to 'Documents', '/documents', class: 'navbar-item' %>
    </div>

    <div class="navbar-end">
      <div class="navbar-item">
        <div class="buttons">
          <%= link_to '/signup', class: 'button is-dark' do %>
            <strong>Sign up</strong>
          <% end %>

          <%= link_to '/login', class: 'button is-light' do %>
            <strong>Log in</strong>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ed</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1">

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'styles', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation" class="notification is-danger">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    <%= form.label :email, class: 'label' %>
    <%= form.text_field :email, class: 'input is-rounded' %>
  </div>

  <div class="field">
    <%= form.label :password, class: 'label' %>
    <%= form.password_field :password, class: 'input is-rounded'  %>
  </div>

  <div class="field">
    <%= form.label :password_confirmation, class: 'label' %>
    <%= form.password_field :password_confirmation, class: 'input is-rounded'  %>
  </div>

  <div class="actions">
    <%= form.submit class: 'button is-dark'%>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1 class="title">Editing User</h1>

<%= render 'form', user: @user %>

<br>
<%= link_to 'Show', @user, class: 'button is-small' %>
<%= link_to 'Back', users_path, class: 'button is-small' %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1 class="title">Users</h1>

<table class="table is-striped is-hoverable">
  <thead>
    <tr>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.email %></td>
        <td>
          <%= link_to user, class: "icon has-text-dark" do %>
            <%# <span class="icon has-text-info"> %>
              <i class="fas fa-info"></i>
            <%# </span> %>
          <% end %>
        </td>
        <td>
          <%= link_to edit_user_path(user) do %>
            <span class="icon has-text-dark">
              <i class="fas fa-edit"></i>
            </span>
          <% end %>
        </td>
        <td>
          <%= link_to user, method: :delete, data: { confirm: 'Are you sure?' } do %>
            <span class="icon has-text-danger">
              <i class="fas fa-trash"></i>
            </span>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path, class: "button is-dark" %>

app/views/users/new.html.erb
<h1 class="title">New User</h1>

<%= render 'form', user: @user %>

<br>

<%= link_to 'Back', users_path, class: 'button is-small is-light' %>

app/views/users/show.html.erb
<p id="notice" class="<%= notice && 'notification is-primary' %>"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<br>

<%= link_to 'Edit', edit_user_path(@user), class: 'button is-small' %>
<%= link_to 'Back', users_path, class: 'button is-small' %>